name: Deploy to HubSpot

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install -g @hubspot/cli

      - name: Create hubspot.config.yml
        run: |
          echo "defaultPortal: ${{ secrets.HUBSPOT_PORTAL_ID }}
portals:
  - name: Production
    portalId: ${{ secrets.HUBSPOT_PORTAL_ID }}
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
" > hubspot.config.yml

      - name: Deploy to HubSpot
        run: hs upload src cms-theme-boilerplate
        env:
          HUBSPOT_PORTAL_ID: ${{ secrets.HUBSPOT_PORTAL_ID }}
          HUBSPOT_PERSONAL_ACCESS_KEY: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
